name: nucleoid
description: nucleoid package
homepage: https://github.com/dart-nucleoid/main
version: 0.2.2

environment:
  sdk: ^3.8.0
resolution: workspace

dependencies:
  shelf: ^1.4.0
  shelf_secure_cookie: ^1.3.0
  loggable: ^1.0.1
  args: ^2.7.0
  yaml: ^3.1.0
  meta: ^1.1.8
  http: ^1.4.0
  io: ^1.0.0
  cooky: ^2.0.0
  nucleoid_built: ^0.2.2
  http_parser: ^4.1.0
  path: ^1.7.0
  pedantic: ^1.8.0
  logging: ^1.3.0
  image: ^4.5.0

dev_dependencies:
  test: ^1.26.0
  build_runner: ^2.4.0
  build_test: ^2.2.0
  nucleoid_generator: ^0.2.2