name: nucleoid_crm
description: nucleoid crm package
homepage: https://flutter.su/nucleoid
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  nucleoid: ^0.1.1
  nucleoid_built: ^0.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.4
  build_test: ^0.10.12+1
  nucleoid_generator: ^0.1.0