name: nucleoid_built
description: nucleoid_built package
homepage: https://github.com/dart-nucleoid/main
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: '>=0.12.0 <2.0.0'
  meta: ^1.1.8

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.7.4
  test: ^1.0.0