targets:
  $default:
    builders:
      node_element_generator|node_element:
        enabled: true
      model_mysql_generator|model_mysql:
        enabled: true

builders:
  node_element:
    target: ":node_element_generator"
    import: "package:nucleoid_generator/builder.dart"
    builder_factories: ["nodeElement"]
    build_extensions: {".dart": [".node_element.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  model_mysql_generator:
    target: ":model_mysql_generator"
    import: "package:nucleoid_generator/builder.dart"
    builder_factories: ["modelMysql"]
    build_extensions: {".dart": [".model_mysql.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]