name: nucleoid_generator
description: nucleoid_generator package
homepage: https://github.com/dart-nucleoid/main
version: 0.2.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  analyzer: ">=0.37.0 <0.40.0"
  meta: ^1.1.8
  nucleoid_built: ^0.2.2

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.7.4
  test: ^1.0.0