name: server_template
description: nucleoid server template project
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  nucleoid: ^1.0.0

dependency_overrides:
  nucleoid:
    path: ../../packages/nucleoid
  nucleoid_built:
    path: ../../packages/nucleoid_built
  nucleoid_generator:
    path: ../../packages/nucleoid_generator

nucleoid:
  assets:
    - assets
  scripts:
    - lib/script/main.dart