name: server_template
description: nucleoid server template project
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.2
  loggable: ^1.0.1
  nucleoid: ^0.2.2
  nucleoid_crm: ^0.2.2
  nucleoid_built: ^0.2.2

dev_dependencies:
  pedantic: ^1.7.0
  build_runner: ^1.7.4
  nucleoid_generator: ^0.2.2

nucleoid:
  assets:
    - assets
  scripts:
    - lib/script/main.dart