name: nucleoid_generator
description: nucleoid_generator package
homepage: https://github.com/dart-nucleoid/main
version: 1.0.0

environment:
  sdk: ^3.8.0
resolution: workspace

dependencies:
  build: ^2.1.0
  source_gen: ^2.0.0
  analyzer: ^7.4.0
  meta: ^1.1.8
  nucleoid_built: ^1.0.0
  collection: ^1.19.0

dev_dependencies:
  test: ^1.26.0
  build_runner: ^2.4.0
  build_test: ^2.2.0