name: nucleoid
description: nucleoid package
homepage: https://github.com/dart-nucleoid/main
version: 0.1.3

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  shelf: ^0.7.5
  shelf_cookie: ^1.1.1
  loggable: ^1.0.1
  args: ^1.5.0
  yaml: ^2.2.0
  meta: ^1.1.8
  http: ^0.12.0+4
  io: ^0.3.3
  cooky: ^1.0.2
  mysql1: ^0.17.1
  nucleoid_built: ^0.1.1
  http_parser: ^3.1.4
  path: ^1.7.0
  pedantic: ^1.8.0
  logging: ^0.11.4

dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.7.4
  build_test: ^0.10.12+1
  nucleoid_generator: ^0.1.0